### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by INHERGUTSGUS** [Exunys/ESP-Script#1]
Hey Im new to lua im assuming i insert the directory in the script as the game im trying to inject into? I made some scripts in C++ and have experience in php. I think I might be brainfarting here

**Comment by Exunys** [comment]
I'm sorry but I didn't understand what you said and why did you open an issue, I suggest you email me at [exunys@gmail.com](mailto:exunys@gmail.com) or dm me on [discord](https://discord.com/users/611111398818316309) so we can talk about what you need in detail but from what I understood is that you don't know how to run the script, you need a roblox luau script executor and a paid one that I suggest and that I use myself is https://x.synapse.to.
